# Assignment #52 - Intro to RSpec
#
# Since the intent for Test-Driven Development is to keep the tests as low-level as possible, the idea is to remove any dependencies to other Models. I assume this is a best practice. I also assume that if one referenced another model (e.g., the 'Post' model), that this RSpec file would have to somehow import the 'Post' RSpec file. Since this dependency is not asserted, then I assume it is sufficient to only require 'rails_helper' for RSpec testing purposes.
=begin
require 'rails_helper'

describe Vote do
describe "validations" do
       # Assignment #52 - Intro to RSpec
       #
       # I added an underscore to 'value validation' in order to follow the proper naming convention. Also, I assume that this functionality is best built in as an instance method and not as a class method, which is why the method name is preceded with a hash symbol. One assumes the 'Vote' model will be instantiated and assigned to an object instance variable. As with the 'Post' model RSpec test, perhaps this would be done in a 'before' block, as in the following example.
       #
       # before do
       #    @vote = Vote.create(value_validation: 0)
       # end
       #
       # Given the checkpoint's discussion on 'Red, Green, Refactor', I assume the 'Vote' object instance variable should hold a reference to a 'Vote' object that has a 'value_validation' value that initially intensionally fails the '#value_validation' RSpec test.
       describe "#value_validation" do
           it "only allows -1 or 1 as values" do
               expect( @vote.value_validation ).to eq(-1)
               expect( @vote.value_validation ).to eq(1)
           end
       end
    end
end
=end

# Assignment #52 - Intro to RSpec
#
# Dalibor's comments:
#      - You need to enter specific expectations in your tests. One of the possible solutions:
#
# Checkpoint #53 - Voting
#
# Create a Vote model with attributes for value (an integer), 'user_id' and 'post_id'.
#
# Hint: Use 'user:references' and 'post:references' in your generator to add the IDs and the relevant relationships in the model files.
#
# Note:  This file was autogenerated when the Vote model and migration file was created. However, the Checkpoint #53 - Voting refers back to the Vote RSpec model creating in Checkpoint #52 - Intro to RSpec. Therefore, I backed up this auto-generated Vote RSpec file ('vote_spec.rb_BAK') in favor of using the existing 'vote_spec.rb' file.

# Checkpoint #53 - Voting
#
# If you copied our test scaffold verbatim, you should get an uninitialized constant Vote (NameError) error. This error is because we forgot to require rails_helper, which tells our spec where to look for its associated models. Add that now.
require 'rails_helper'

describe Vote do
  describe "validations" do
    it "only allows -1 or 1 as values" do
      up_vote = Vote.new(value: 1)
      # Checkpoint #53 - Voting
      #
      # Dalibor's comments:
      #     - I checked out branch from github. I needed to add vote validation
      #       and use different rspec matcher to get the same output.
      #     - Enter the same corrections as above, and it should work.
      #
      #expect(up_vote.valid?).to be_true
      expect(up_vote).to be_valid
      
      down_vote = Vote.new(value: -1)
      # Checkpoint #53 - Voting
      #
      # Dalibor's comments:
      #     - I checked out branch from github. I needed to add vote validation
      #       and use different rspec matcher to get the same output.
      #     - Enter the same corrections as above, and it should work.
      #
      #expect(down_vote.valid?).to be_true
      expect(down_vote).to be_valid
      
      invalid_vote = Vote.new(value: 2)
      # Checkpoint #53 - Voting
      #
      # Dalibor's comments:
      #     - I checked out branch from github. I needed to add vote validation
      #       and use different rspec matcher to get the same output.
      #     - Enter the same corrections as above, and it should work.
      #
      #expect(invalid_vote.valid?).to be_false
      expect(invalid_vote).to be_invalid
    end
  end
end