# Checkpoint #40 - Topics and Posts
class TopicPolicy < ApplicationPolicy
    def index?
        true
    end
    
    def create?
        user.present? && user.admin?
    end
    
    def update?
        create?
    end
    
    # Checkpoint #56 - Private Topics
    #
    # Left as is, a user who is not signed-in could still enter the specific URL of a private topic to see it. For example, go back to your console and find the id of the non-public topic you created.
    #
    # Obviously, we need to prevent this behavior, so let's add the requisite authorizations. First we'll need to add a new rule to the TopicPolicy so that private topics will only be visible to signed-in users.
    #
    # Note the autogenerated public? method Rails gives us to query the boolean value. It's equivalent to public, but makes its true-false role clearer.
    def show?
        record.public? || user.present?
    end
end