# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#  Daibor's recommendation from Sat, 15 Aug 2015 at 5:40 PM
#
# ▶ cat config/application.yml 
# SECRET_KEY_BASE: 'b7f14945841e3f8da6165fa8d300acab8ec429d0289516ec888c36ea0054b1bb2e6edbe512209cc7b74109a48e3c79b41d99abafdbfc721bb0deaa40dc75a713'
# SENDGRID_PASSWORD: '1212'
# SENDGRID_USERNAME: '1212'
#
# ▶ cat config/secrets.yml 
# Be sure to restart your server when you modify this file.
#
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
#
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
#
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#
# development:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#
# test:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
#
# Do not keep production secrets in the repository,
# instead read values from the environment.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  #secret_key_base: 10d94a6b98b4b5d2ac172e367bede61f16d3537ff99f20e6abd80265f94b8da4713781a7813baf9877e1110390ccb6cf31f806e72e02b1323ff7362dbc2aa227
  
  # Checktpoint 37: Authentication Continued
  #
  # This makes your Development and Production tokens distinct, as opposed
  # to the case below. For simplicity, add SECRET_KEY_BASE to your
  # application.yml instead, and use Figaro to sync the tokens on Production
  # and Development. Then set the Development key to equal the same ENV-stored
  # token as the Production key in secrets.yml.
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>